<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">isInStringList</value>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">dHJ5ew0KCUlEYXRhQ3Vyc29yIGN1cnNvciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KCVN0cmlu
Z1tdIGxpc3QgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nQXJyYXkoY3Vyc29yLCJsaXN0Iik7DQoJU3Ry
aW5nIGl0ZW0gPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGN1cnNvciwiaXRlbSIpOw0KCWJvb2xlYW4g
cmVzdWx0YXQgPSBmYWxzZTsNCgkNCgkvKlBhcmNvdXJzIGRlIGxhIGxpc3RlIGV0IHZcdTAwRTly
aWZpY2F0aW9uIGRlIGxhIHByXHUwMEU5c2VuY2UgZCciaXRlbSIgZGFucyAibGlzdCIqLw0KCWlm
KGxpc3QgIT0gbnVsbCl7DQoJCWZvcihpbnQgaSA9IDA7IGkgPCBsaXN0Lmxlbmd0aCAmJiAhcmVz
dWx0YXQ7IGkrKyl7DQoJCQlyZXN1bHRhdCA9IGxpc3RbaV0uZXF1YWxzKGl0ZW0pOw0KCQl9DQoJ
fQ0KDQoJLypSZW5zZWlnbmVtZW50IGR1IHJcdTAwRTlzdWx0YXQgZGFucyBsZSBwaXBlbGluZSov
DQoJaWYocmVzdWx0YXQpDQoJCWN1cnNvci5pbnNlcnRBZnRlcigicmVzdWx0IiwgInRydWUiKTsN
CgllbHNlDQoJCWN1cnNvci5pbnNlcnRBZnRlcigicmVzdWx0IiwgImZhbHNlIik7DQoJDQoJLypE
ZXN0cnVjdGlvbiBkdSBjdXJzZXVyKi8NCgljdXJzb3IuZGVzdHJveSgpOw0KfQ0KY2F0Y2goRXhj
ZXB0aW9uIGUpew0KCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJbQWRtaW5JUy51dGlsczpp
c0luU3RyaW5nTGlzdF0gOiAiICsgZS50b1N0cmluZygpKTsNCn0NCg==</value>
</Values>
